steps:
- name: 'gcr.io/cloud-builders/bazel'
  env:
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
  args: ['test', '--config=remote', '//pkg/apis/contrail/v1alpha1/tests:go_default_test']
- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '--config=remote', '//cmd/manager:contrail-operator-push' ]
  env:
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '--config=remote', '//cmd/manager:contrail-operator-push-latest' ]
  env:
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '--config=remote', '//statusmonitor:contrail-statusmonitor-push' ]
  env:
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '--config=remote', '//statusmonitor:contrail-statusmonitor-push-latest' ]
  env:
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
timeout: '1h'
options:
  machineType: 'N1_HIGHCPU_8'
