steps:
- name: 'gcr.io/cloud-builders/bazel'
  args: ['build', '//cmd/manager:contrail-operator-push' ]
- name: 'gcr.io/cloud-builders/bazel'
  args: ['test', '//pkg/apis/contrail/v1alpha1/tests:go_default_test']
