steps:
  - name: "gcr.io/cloud-builders/bazel"
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
    args: ["test", "//..."]
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//cmd/manager:contrail-operator-push"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//cmd/manager:contrail-operator-push-latest"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//statusmonitor:contrail-statusmonitor-push"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//statusmonitor:contrail-statusmonitor-push-latest"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//contrail-provisioner:contrail-provisioner-push"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//contrail-provisioner:contrail-provisioner-push-latest"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//ringcontroller:ringcontroller-push"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
  - name: "gcr.io/cloud-builders/bazel"
    args: ["run", "//ringcontroller:ringcontroller-push-latest"]
    env:
      - BUILD_ID=$BUILD_ID
      - COMMIT_SHA=$COMMIT_SHA
      - SHORT_SHA=$SHORT_SHA
      - REPO_NAME=$REPO_NAME
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - REVISION_ID=$REVISION_ID
timeout: "1h"
options:
  machineType: "N1_HIGHCPU_8"
