steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "run"
      - "--volume=/var/run/docker.sock:/var/run/docker.sock"
      - "--volume=/workspace:/workspace"
      - "kaweue/testrunner:4"
      - "-c"
      - "/workspace/test/gcb/run_e2e_test.sh"

timeout: "600s"
options:
  machineType: "N1_HIGHCPU_8"
