steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '-d'
  - '--name=kind'
  - '--volume=/var/run/docker.sock:/var/run/docker.sock'
  - '--entrypoint=/bin/bash'
  - 'kaweue/testrunner:3'
  - '-c'
  - 'kind create cluster; kind delete cluster'

timeout: '600s'
options:
  machineType: 'N1_HIGHCPU_8'
