apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    nodeSelector:
      node-role.kubernetes.io/master: ""
    keystoneSecretInstance : cluster1-admin-password
    imagePullSecrets:
      - contrail-registry
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        serviceConfiguration:
          containers:
            - name: cassandra
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/cassandra:3.11.4
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: init2
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          analyticsDataTTL: 2
          analyticsConfigAuditTTL: 2160
          analyticsFlowTTL: 1
          analyticsStatisticsTTL: 2
          containers:
            - name: analyticsapi
              image: <CONTRAIL_REGISTRY>/contrail-analytics-api:<CONTRAIL_VERSION>
            - name: api
              image: <CONTRAIL_REGISTRY>/contrail-controller-config-api:<CONTRAIL_VERSION>
            - name: collector
              image: <CONTRAIL_REGISTRY>/contrail-analytics-collector:<CONTRAIL_VERSION>
            - name: devicemanager
              image: <CONTRAIL_REGISTRY>/contrail-controller-config-devicemgr:<CONTRAIL_VERSION>
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: dnsmasq
              image: <CONTRAIL_REGISTRY>/contrail-controller-config-dnsmasq:<CONTRAIL_VERSION>
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: init2
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/busybox:1.31
            - name: redis
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/redis:4.0.2
            - name: schematransformer
              image: <CONTRAIL_REGISTRY>/contrail-controller-config-schema:<CONTRAIL_VERSION>
            - name: servicemonitor
              image: <CONTRAIL_REGISTRY>/contrail-controller-config-svcmonitor:<CONTRAIL_VERSION>
            - name: queryengine
              image: <CONTRAIL_REGISTRY>/contrail-analytics-query-engine:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: <CONTRAIL_REGISTRY>/contrail-statusmonitor:<CONTRAIL_VERSION>
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: control
              image: <CONTRAIL_REGISTRY>/contrail-controller-control-control:<CONTRAIL_VERSION>
            - name: dns
              image: <CONTRAIL_REGISTRY>/contrail-controller-control-dns:<CONTRAIL_VERSION>
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: named
              image: <CONTRAIL_REGISTRY>/contrail-controller-control-named:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: <CONTRAIL_REGISTRY>/contrail-statusmonitor:<CONTRAIL_VERSION>
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          replicas: 1
        serviceConfiguration:
          containers:
          - name: init
            image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
          - name: provisioner
            image: <CONTRAIL_REGISTRY>/contrail-operator-provisioner:<CONTRAIL_VERSION>
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        serviceConfiguration:
          containers:
          - name: init
            image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
          - name: rabbitmq
            image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: redis
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/redis:4.0.2
            - name: webuijob
              image: <CONTRAIL_REGISTRY>/contrail-controller-webui-job:<CONTRAIL_VERSION>
            - name: webuiweb
              image: <CONTRAIL_REGISTRY>/contrail-controller-webui-web:<CONTRAIL_VERSION>
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
        serviceConfiguration:
          containers:
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: conf-init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: zookeeper
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/zookeeper:3.5.5
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          containers:
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: kubemanager
              image: <CONTRAIL_REGISTRY>/contrail-kubernetes-kube-manager:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: <CONTRAIL_REGISTRY>/contrail-statusmonitor:<CONTRAIL_VERSION>
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          hostNetworkService: true
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermasternodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          contrailStatusImage: <CONTRAIL_REGISTRY>/contrail-status:<CONTRAIL_VERSION>
          containers:
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: nodeinit
              image: <CONTRAIL_REGISTRY>/contrail-node-init:<CONTRAIL_VERSION>
            - name: vrouteragent
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-agent:<CONTRAIL_VERSION>
            - name: vroutercni
              image: <CONTRAIL_REGISTRY>/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: vrouterkernelbuildinit
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-kernel-build-init:<CONTRAIL_VERSION>
            - name: vrouterkernelinit
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-kernel-init:<CONTRAIL_VERSION>
            - name: multusconfig
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouterworkernodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          controlInstance: control1
          contrailStatusImage: <CONTRAIL_REGISTRY>/contrail-status:<CONTRAIL_VERSION>
          containers:
            - name: init
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: nodeinit
              image: <CONTRAIL_REGISTRY>/contrail-node-init:<CONTRAIL_VERSION>
            - name: vrouteragent
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-agent:<CONTRAIL_VERSION>
            - name: vroutercni
              image: <CONTRAIL_REGISTRY>/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: vrouterkernelbuildinit
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-kernel-build-init:<CONTRAIL_VERSION>
            - name: vrouterkernelinit
              image: <CONTRAIL_REGISTRY>/contrail-vrouter-kernel-init:<CONTRAIL_VERSION>
            - name: multusconfig
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/busybox:1.31

    contrailCNIs:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cnimasternodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          containers:
            - name: vroutercni
              image: <CONTRAIL_REGISTRY>/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: multusconfig
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cniworkernodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          controlInstance: control1
          containers:
            - name: vroutercni
              image: <CONTRAIL_REGISTRY>/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: multusconfig
              image: <CONTRAIL_REGISTRY>/common-docker-third-party/contrail/busybox:1.31
    contrailmonitor:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: contrailmonitor
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          rabbitmqInstance: rabbitmq1
          zookeeperInstance: zookeeper1
          webuiInstance: webui1
          configInstance: config1
          controlInstance: control1
          provisionmanagerInstance: provmanager1

