apiVersion: v1
kind: PersistentVolume
metadata:
  name: 2-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/volumes/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
  persistentVolumeReclaimPolicy: Retain
