kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contrail-operator
  namespace: contrail
subjects:
- kind: ServiceAccount
  name: contrail-operator
  namespace: contrail
roleRef:
  kind: Role
  name: contrail-operator
  apiGroup: rbac.authorization.k8s.io