apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: contrail-operator
  namespace: contrail
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - contrail-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - contrail.juniper.net
  resources:
  - '*'
  - managers
  - cassandras
  - zookeepers
  - rabbitmqs
  - controls
  - kubemanagers
  - webuis
  - vrouters
  - provisionmanagers
  - contrailcommands
  - swiftstorages
  - keystones
  - swifts
  - memcacheds
  verbs:
  - '*'
- apiGroups:
  - storage
  resources:
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - contrail
  resources:
  - '*'
  verbs:
  - '*'
