---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
  keystoneSecretInstance: cluster1-admin-password
  services:
    keystone:
      metadata:
        name: keystone
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          memcachedInstance: "memcached"
          postgresInstance: postgres
          listenPort: 5555
          containers:
            - name: wait-for-ready-conf
              image: registry:5000/common-docker-third-party/contrail/busybox:1.31
            - name: keystoneDbInit
              image: registry:5000/common-docker-third-party/contrail/postgresql-client:1.0
            - name: keystoneInit
              image: registry:5000/common-docker-third-party/contrail/centos-binary-keystone:train-2005
            - name: keystone
              image: registry:5000/common-docker-third-party/contrail/centos-binary-keystone:train-2005
    postgres:
      metadata:
        name: postgres
      spec:
        containers:
          - name: postgres
            image: registry:5000/common-docker-third-party/contrail/postgres:12.2
          - name: wait-for-ready-conf
            image: registry:5000/common-docker-third-party/contrail/busybox:1.31
    memcached:
      metadata:
        name: memcached
        namespace: contrail
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: memcached
              image: "registry:5000/common-docker-third-party/contrail/centos-binary-memcached:train-2005"
    swift:
      metadata:
        name: swift
      spec:
        serviceConfiguration:
          credentialsSecretName: "swift-credentials-secret"
          containers:
            - name: ringcontroller
              image: registry:5000/contrail-operator/engprod-269421/ringcontroller:master.latest
          swiftProxyConfiguration:
            memcachedInstance: "memcached"
            keystoneInstance: "keystone"
            listenPort: 5080
            containers:
              - name: init
                image: registry:5000/common-docker-third-party/contrail/centos-binary-kolla-toolbox:train-2005
              - name: wait-for-ready-conf
                image: registry:5000/common-docker-third-party/contrail/busybox:1.31
              - name: api
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-proxy-server:train-2005
          swiftStorageConfiguration:
            accountBindPort: 6001
            containerBindPort: 6002
            objectBindPort: 6000
            device: d1
            containers:
              - name: swiftStorageInit
                image: registry:5000/common-docker-third-party/contrail/busybox:1.31
              - name: swiftObjectExpirer
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-object-expirer:train-2005
              - name: swiftObjectUpdater
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-object:train-2005
              - name: swiftObjectReplicator
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-object:train-2005
              - name: swiftObjectAuditor
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-object:train-2005
              - name: swiftObjectServer
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-object:train-2005
              - name: swiftContainerUpdater
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-container:train-2005
              - name: swiftContainerReplicator
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-container:train-2005
              - name: swiftContainerAuditor
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-container:train-2005
              - name: swiftContainerServer
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-container:train-2005
              - name: swiftAccountReaper
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-account:train-2005
              - name: swiftAccountReplicator
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-account:train-2005
              - name: swiftAccountAuditor
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-account:train-2005
              - name: swiftAccountServer
                image: registry:5000/common-docker-third-party/contrail/centos-binary-swift-account:train-2005
