apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 02-master-pv-mounts
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      directories:
        - filesystem: "root"
          path: "/mnt/volumes/1"
          mode: 0755
        - filesystem: "root"
          path: "/mnt/volumes/2"
          mode: 0755
        - filesystem: "root"
          path: "/mnt/volumes/3"
          mode: 0755
        - filesystem: "root"
          path: "/mnt/volumes/4"
          mode: 0755
        - filesystem: "root"
          path: "/mnt/volumes/5"
          mode: 0755
