apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: contrailstatusmonitors.contrail.juniper.net
spec:
  additionalPrinterColumns:
  - JSONPath: .status
    description: Number of instances in group
    name: Status
    type: string
  - JSONPath: .errornotes
    description: Number of instances in group
    name: Errornotes
    type: string
  group: contrail.juniper.net
  names:
    kind: Contrailstatusmonitor
    listKind: ContrailstatusmonitorList
    plural: contrailstatusmonitors
    singular: contrailstatusmonitor
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: Contrailstatusmonitor is the Schema for the contrailstatusmonitors
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        errornotes:
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        status:
          type: string
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
