apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 3
    keystoneSecretInstance : cluster1-admin-password
    imagePullSecrets:
      - contrail-registry
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: cassandra
              image: cassandra:3.11.4
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          analyticsDataTTL: 2
          analyticsConfigAuditTTL: 2160
          analyticsFlowTTL: 1
          analyticsStatisticsTTL: 2
          containers:
            - name: analyticsapi
              image: hub.juniper.net/contrail/contrail-analytics-api:2008.121-rhel
            - name: api
              image: hub.juniper.net/contrail/contrail-controller-config-api:2008.121-rhel
            - name: collector
              image: hub.juniper.net/contrail/contrail-analytics-collector:2008.121-rhel
            - name: devicemanager
              image: hub.juniper.net/contrail/contrail-controller-config-devicemgr:2008.121-rhel
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: dnsmasq
              image: hub.juniper.net/contrail/contrail-controller-config-dnsmasq:2008.121-rhel
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: busybox:1.31
            - name: redis
              image: redis:4.0.2
            - name: schematransformer
              image: hub.juniper.net/contrail/contrail-controller-config-schema:2008.121-rhel
            - name: servicemonitor
              image: hub.juniper.net/contrail/contrail-controller-config-svcmonitor:2008.121-rhel
            - name: queryengine
              image: hub.juniper.net/contrail/contrail-analytics-query-engine:2008.121-rhel
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2008.121
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: control
              image: hub.juniper.net/contrail/contrail-controller-control-control:2008.121-rhel
            - name: dns
              image: hub.juniper.net/contrail/contrail-controller-control-dns:2008.121-rhel
            - name: init
              image: python:3.8.2-alpine
            - name: named
              image: hub.juniper.net/contrail/contrail-controller-control-named:2008.121-rhel
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2008.121
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          replicas: 1
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: provisioner
            image: hub.juniper.net/contrail/contrail-operator-provisioner:2008.121
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: rabbitmq
            image: rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: redis
              image: redis:4.0.2
            - name: webuijob
              image: hub.juniper.net/contrail/contrail-controller-webui-job:2008.121-rhel
            - name: webuiweb
              image: hub.juniper.net/contrail/contrail-controller-webui-web:2008.121-rhel
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: zookeeper
              image: docker.io/zookeeper:3.5.5
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: kubemanager
              image: hub.juniper.net/contrail/contrail-kubernetes-kube-manager:2008.121-rhel
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2008.121
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          hostNetworkService: true
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermasternodes
      spec:
        commonConfiguration:
          create: true
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          contrailStatusImage: hub.juniper.net/contrail/contrail-status:2008.121-rhel
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail/contrail-node-init:2008.121-rhel
            - name: vrouteragent
              image: hub.juniper.net/contrail/contrail-vrouter-agent:2008.121-rhel
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2008.121-rhel
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-build-init:2008.121-rhel
            - name: vrouterkernelinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-init:2008.121-rhel
            - name: multusconfig
              image: busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouterworkernodes
      spec:
        commonConfiguration:
          create: true
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          contrailStatusImage: hub.juniper.net/contrail/contrail-status:2008.121-rhel
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail/contrail-node-init:2008.121-rhel
            - name: vrouteragent
              image: hub.juniper.net/contrail/contrail-vrouter-agent:2008.121-rhel
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2008.121-rhel
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-build-init:2008.121-rhel
            - name: vrouterkernelinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-init:2008.121-rhel
            - name: multusconfig
              image: busybox:1.31
