apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: swiftstorages.contrail.juniper.net
spec:
  group: contrail.juniper.net
  names:
    kind: SwiftStorage
    listKind: SwiftStorageList
    plural: swiftstorages
    singular: swiftstorage
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SwiftStorage is the Schema for the swiftstorages API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SwiftStorageSpec defines the desired state of SwiftStorage
          properties:
            serviceConfiguration:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                accountBindPort:
                  type: integer
                containerBindPort:
                  type: integer
                containers: {}
                device:
                  type: string
                objectBindPort:
                  type: integer
                ringPersistentVolumeClaim:
                  type: string
                swiftConfSecretName:
                  type: string
              type: object
          required:
          - serviceConfiguration
          type: object
        status:
          description: SwiftStorageStatus defines the observed state of SwiftStorage
          properties:
            active:
              type: boolean
          required:
          - active
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
