---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: cassandra
            image: cassandra:3.11.4
          - name: init
            image: python:alpine
          - name: init2
            image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: analyticsapi
            image: opencontrailnightly/contrail-analytics-api:1910-latest
          - name: api
            image: opencontrailnightly/contrail-controller-config-api:1910-latest
          - name: collector
            image: opencontrailnightly/contrail-analytics-collector:1910-latest
          - name: devicemanager
            image: opencontrailnightly/contrail-controller-config-devicemgr:1910-latest
          - name: dnsmasq
            image: opencontrailnightly/contrail-external-dnsmasq:1910-latest
          - name: init
            image: python:alpine
          - name: init2
            image: busybox
          - name: redis
            image: redis:4.0.2
          - name: schematransformer
            image: opencontrailnightly/contrail-controller-config-schema:1910-latest
          - name: servicemonitor
            image: opencontrailnightly/contrail-controller-config-svcmonitor:1910-latest
          - name: queryengine
            image: opencontrailnightly/contrail-analytics-query-engine:1910-latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: control
            image: opencontrailnightly/contrail-controller-control-control:1910-latest
          - name: dns
            image: opencontrailnightly/contrail-controller-control-dns:1910-latest
          - name: init
            image: python:alpine
          - name: named
            image: opencontrailnightly/contrail-controller-control-named:1910-latest
          - name: statusmonitor
            image: kaweue/contrail-statusmonitor:master-180ab9
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: kubemanager
            image: michaelhenkel/contrail-kubernetes-kube-manager:1910-latest
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
          replicas: 1
        serviceConfiguration:
          containers:
          - name: init
            image: python:alpine
          - name: provisioner
            image: kaweue/contrail-operator-provisioner:master.1175
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:alpine
          - name: rabbitmq
            image: rabbitmq:3.7
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermaster
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: nodeinit
            image: opencontrailnightly/contrail-node-init:1910-latest
          - name: vrouteragent
            image: opencontrailnightly/contrail-vrouter-agent:1910-latest
          - name: vroutercni
            image: michaelhenkel/contrailcni:v0.0.1
          - name: vrouterkernelbuildinit
            image: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
          - name: vrouterkernelinit
            image: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
          controlInstance: control1
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouternodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.opencontrail.org: vrouter
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: nodeinit
            image: opencontrailnightly/contrail-node-init:1910-latest
          - name: vrouteragent
            image: opencontrailnightly/contrail-vrouter-agent:1910-latest
          - name: vroutercni
            image: michaelhenkel/contrailcni:v0.0.1
          - name: vrouterkernelbuildinit
            image: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
          - name: vrouterkernelinit
            image: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
          controlInstance: control1
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: redis
            image: redis:4.0.2
          - name: webuijob
            image: opencontrailnightly/contrail-controller-webui-job:1910-latest
          - name: webuiweb
            image: opencontrailnightly/contrail-controller-webui-web:1910-latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:alpine
          - name: zookeeper
            image: docker.io/zookeeper:3.5.5
