apiVersion: contrail.juniper.net/v1alpha1
kind: ContrailCNI
metadata:
  name: example-contrailcni
  namespace: contrail
spec:
    serviceConfiguration:
        Containers:
          - name: vroutercni
            image: dysproz/cni-init
    commonConfiguration:
      create: true

