apiVersion: contrail.juniper.net/v1alpha1
kind: Keystone
metadata:
  name: keystone
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    nodeSelector:
      node-role.kubernetes.io/master: ""
  serviceConfiguration:
    memcachedInstance: "memcached"
    postgresInstance: "postgres"
    listenPort: 5555
