apiVersion: contrail.juniper.net/v1alpha1
kind: Command
metadata:
  name: command
spec:
  commonConfiguration:
    hostNetwork: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    nodeSelector:
      node-role.kubernetes.io/master: ""
  serviceConfiguration:
    postgresInstance: "postgres"

