apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    nodeSelector:
      node-role.kubernetes.io/master: ""
    keystoneSecretInstance : cluster1-admin-password
    imagePullSecrets:
      - contrail-registry
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        serviceConfiguration:
          containers:
            - name: cassandra
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/cassandra:3.11.4
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: init2
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          analyticsDataTTL: 2
          analyticsConfigAuditTTL: 2160
          analyticsFlowTTL: 1
          analyticsStatisticsTTL: 2
          containers:
            - name: analyticsapi
              image: hub.juniper.net/contrail/contrail-analytics-api:2011.138
            - name: api
              image: hub.juniper.net/contrail/contrail-controller-config-api:2011.138
            - name: collector
              image: hub.juniper.net/contrail/contrail-analytics-collector:2011.138
            - name: devicemanager
              image: hub.juniper.net/contrail/contrail-controller-config-devicemgr:2011.138
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: dnsmasq
              image: hub.juniper.net/contrail/contrail-controller-config-dnsmasq:2011.138
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: init2
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/busybox:1.31
            - name: redis
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/redis:4.0.2
            - name: schematransformer
              image: hub.juniper.net/contrail/contrail-controller-config-schema:2011.138
            - name: servicemonitor
              image: hub.juniper.net/contrail/contrail-controller-config-svcmonitor:2011.138
            - name: queryengine
              image: hub.juniper.net/contrail/contrail-analytics-query-engine:2011.138
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2011.138
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: control
              image: hub.juniper.net/contrail/contrail-controller-control-control:2011.138
            - name: dns
              image: hub.juniper.net/contrail/contrail-controller-control-dns:2011.138
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: named
              image: hub.juniper.net/contrail/contrail-controller-control-named:2011.138
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2011.138
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          replicas: 1
        serviceConfiguration:
          containers:
          - name: init
            image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
          - name: provisioner
            image: hub.juniper.net/contrail/contrail-operator-provisioner:2011.138
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        serviceConfiguration:
          containers:
          - name: init
            image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
          - name: rabbitmq
            image: hub.juniper.net/contrail/common-docker-third-party/contrail/rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: redis
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/redis:4.0.2
            - name: webuijob
              image: hub.juniper.net/contrail/contrail-controller-webui-job:2011.138
            - name: webuiweb
              image: hub.juniper.net/contrail/contrail-controller-webui-web:2011.138
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
        serviceConfiguration:
          containers:
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: conf-init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: zookeeper
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/zookeeper:3.5.5
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          containers:
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: kubemanager
              image: hub.juniper.net/contrail/contrail-kubernetes-kube-manager:2011.138
            - name: statusmonitor
              image: hub.juniper.net/contrail/contrail-statusmonitor:2011.138
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          hostNetworkService: true
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermasternodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          contrailStatusImage: hub.juniper.net/contrail/contrail-status:2011.138
          containers:
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail/contrail-node-init:2011.138
            - name: vrouteragent
              image: hub.juniper.net/contrail/contrail-vrouter-agent:2011.138
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2011.138
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-build-init:2011.138
            - name: vrouterkernelinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-init:2011.138
            - name: multusconfig
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouterworkernodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          contrailStatusImage: hub.juniper.net/contrail/contrail-status:2011.138
          containers:
            - name: init
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail/contrail-node-init:2011.138
            - name: vrouteragent
              image: hub.juniper.net/contrail/contrail-vrouter-agent:2011.138
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2011.138
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-build-init:2011.138
            - name: vrouterkernelinit
              image: hub.juniper.net/contrail/contrail-vrouter-kernel-init:2011.138
            - name: multusconfig
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/busybox:1.31
    contrailCNIs:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cnimasternodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          containers:
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2011.138
            - name: multusconfig
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cniworkernodes
      spec:
        commonConfiguration:
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          controlInstance: control1
          containers:
            - name: vroutercni
              image: hub.juniper.net/contrail/contrail-kubernetes-cni-init:2011.138
            - name: multusconfig
              image: hub.juniper.net/contrail/common-docker-third-party/contrail/busybox:1.31
    contrailmonitor:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: contrailmonitor
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          rabbitmqInstance: rabbitmq1
          zookeeperInstance: zookeeper1
          webuiInstance: webui1
          configInstance: config1
          controlInstance: control1
          provisionmanagerInstance: provmanager1
