---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-operator
  namespace: contrail
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contrail-operator
  template:
    metadata:
      labels:
        name: contrail-operator
    spec:
      serviceAccountName: contrail-operator
      hostNetwork: true
      tolerations:
      - key: node.kubernetes.io/not-ready
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: contrail-operator
          image: registry:5000/contrail-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "contrail-operator"
---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            cassandra:
              image: cassandra:3.11.4
            init:
              image: python:alpine
            init2:
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            analyticsapi:
              image: opencontrailnightly/contrail-analytics-api:1910-latest
            api:
              image: opencontrailnightly/contrail-controller-config-api:1910-latest
            collector:
              image: opencontrailnightly/contrail-analytics-collector:1910-latest
            devicemanager:
              image: opencontrailnightly/contrail-controller-config-devicemgr:1910-latest
            init:
              image: python:alpine
            init2:
              image: busybox
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            redis:
              image: redis:4.0.2
            schematransformer:
              image: opencontrailnightly/contrail-controller-config-schema:1910-latest
            servicemonitor:
              image: opencontrailnightly/contrail-controller-config-svcmonitor:1910-latest
            queryengine:
              image: opencontrailnightly/contrail-analytics-query-engine:1910-latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            control:
              image: opencontrailnightly/contrail-controller-control-control:1910-latest
            dns:
              image: opencontrailnightly/contrail-controller-control-dns:1910-latest
            init:
              image: python:alpine
            named:
              image: opencontrailnightly/contrail-controller-control-named:1910-latest
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            statusmonitor:
              image: michaelhenkel/contrail-statusmonitor:debug
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          replicas: 1
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            provisioner:
              image: michaelhenkel/contrail-provisioner:debug
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            rabbitmq:
              image: rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            redis:
              image: redis:4.0.2
            webuijob:
              image: opencontrailnightly/contrail-controller-webui-job:1910-latest
            webuiweb:
              image: opencontrailnightly/contrail-controller-webui-web:1910-latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            zookeeper:
              image: docker.io/zookeeper:3.5.5
    contrailCommand:
      metadata:
        name: command
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          configAPIURL: https://kind-control-plane:8082
          telemetryURL: https://kind-control-plane:8081
          postgresInstance: postgres
          adminUsername: admin
          adminPassword: contrail123
          image: registry:5000/contrail-command:1912-latest
    keystone:
      metadata:
        name: keystone
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          postgresInstance: postgres
          listenPort: 5555
          imageRegistry: kolla
    postgres:
      metadata:
        name: postgres
      spec:
        image: postgres
