---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    replicas: 1
    hostNetwork: true
    imagePullSecrets:
    - contrail-nightly
  services:
    contrailCommand:
      metadata:
        name: command
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ''
        serviceConfiguration:
          postgresInstance: postgres
          adminUsername: admin
          adminPassword: contrail123
          image: 172.17.14.127:5000/contrail-command:latest
    keystone:
      metadata:
        name: keystone
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ''
        serviceConfiguration:
          postgresInstance: postgres
          listenPort: 5555
          imageRegistry: 172.17.14.127:5000
    postgres:
      metadata:
        name: postgres
      spec: 
        image: 172.17.14.127:5000/postgres:latest
