apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 10-worker-static-hostname
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: static-hostname-contrail.service
        enabled: true
        contents: |
          [Unit]
          Description=Sets the static hostname required by Contrail
          After=syslog.target
          
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/bash -c 'echo $(hostname -A) > /etc/hostname'
          StandardOutput=syslog
          StandardError=syslog
          
          [Install]
          WantedBy=basic.target
