---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
    nodeSelector:
      node-role.kubernetes.io/master: ""
    keystoneSecretInstance : cluster1-admin-password
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            cassandra:
              image: cassandra:3.11.4
            init:
              image: python:alpine
            init2:
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            analyticsapi:
              image: opencontrailnightly/contrail-analytics-api:1912-latest
            api:
              image: opencontrailnightly/contrail-controller-config-api:1912-latest
            collector:
              image: opencontrailnightly/contrail-analytics-collector:1912-latest
            devicemanager:
              image: kaweue/contrail-controller-config-devicemgr:dev-5
            dnsmasq:
              image: kaweue/contrail-controller-config-dnsmasq:dev
            init:
              image: python:alpine
            init2:
              image: busybox
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1912-latest
            redis:
              image: redis:4.0.2
            schematransformer:
              image: opencontrailnightly/contrail-controller-config-schema:1912-latest
            servicemonitor:
              image: opencontrailnightly/contrail-controller-config-svcmonitor:1912-latest
            queryengine:
              image: opencontrailnightly/contrail-analytics-query-engine:1912-latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            control:
              image: opencontrailnightly/contrail-controller-control-control:1912-latest
            dns:
              image: opencontrailnightly/contrail-controller-control-dns:1912-latest
            init:
              image: python:alpine
            named:
              image: opencontrailnightly/contrail-controller-control-named:1912-latest
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1912-latest
            statusmonitor:
              image: michaelhenkel/contrail-statusmonitor:debug
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          replicas: 1
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            provisioner:
              image: dysproz/contrail-provisioner
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            rabbitmq:
              image: rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1912-latest
            redis:
              image: redis:4.0.2
            webuijob:
              image: opencontrailnightly/contrail-controller-webui-job:1912-latest
            webuiweb:
              image: opencontrailnightly/contrail-controller-webui-web:1912-latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            zookeeper:
              image: zookeeper:3.5.5
    postgres:
      metadata:
        name: postgres
      spec:
        containers:
          postgres: 
            image: postgres
    memcached:
      metadata:
        name: memcached
        namespace: contrail
      spec:
        serviceConfiguration:
          container:
            image: kolla/centos-binary-memcached:train
    keystone:
      metadata:
        name: keystone
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
        serviceConfiguration:
          memcachedInstance: "memcached"
          postgresInstance: postgres
          listenPort: 5555
          containers:
            keystoneDbInit:
              image: tmaier/postgresql-client
            keystoneInit:
              image: kolla/centos-binary-keystone:train
            keystone:
              image: kolla/centos-binary-keystone:train
            keystoneSsh:
              image: kolla/centos-binary-keystone-ssh:train
            keystoneFernet:
              image: kolla/centos-binary-keystone-fernet:train

